### ISSUE TITLE
Infografia Unidad I

### ISSUE THREAD

**Issue by Nelsy21** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Nelsy21#2]
[Infografía Fases de Gestion de Proyectos_unidad1_Infografia1.pdf](https://github.com/user-attachments/files/16753013/Infografia.Fases.de.Gestion.de.Proyectos_unidad1_Infografia1.pdf)

**Comment by Irvingzr16** [comment]
Redacción y ortografía: 16.67%
Exposición de ideas centrales:16.67%
Organización de la información: 16.67%
Uso de imagines y colores: 16.67%
Presentación visual: 16.67%
Referencias y presentación: 16.67%

porcentaje final:100%


**Calificación final: 20/20**

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
